### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by ethanfurman** [paul-wolf/yewdoc-client#3]
`Register.pushtags()` has an unused `r`.

`YewStore.get_tag_associations()` has an unused `tags`.

`YewStore.get_globals()` has an unused `v`.

`YewStore.get_docs()` has an unused `doc`.

`YewStore.get()` has an unused `doc`.

`get_user_email()` references `self` but has none.

`user_pref()` has an unused username.

`pdoc()` has an unused `p`.

`sync()` has an unused `docs_remote`

**Comment by paul-wolf** [comment]
I think I got all of these now. Cheers.
